backend:
  name: github
  repo: artverse1studios-beep/ArtVerse
  branch: main
  base_url: https://cms-auth.artverse1-studios.workers.dev

media_folder: "images/campaigns"
public_folder: "/images/campaigns"

collections:
  - name: "artists"
    label: "Featured Artists"
    folder: "data"
    create: false  # Disable creating new files
    files:
      - file: "data/campaigns.json"
        label: "Artists List"
        name: "campaigns"
        fields:
          - { label: "Artists", name: "artists", widget: "list", fields:
              - { label: "Artist Name", name: "artist_name", widget: "string" }
              - { label: "Intro Bio", name: "intro", widget: "markdown" }
              - { label: "Instagram Link", name: "instagram_link", widget: "string" }
              - { label: "Picture", name: "picture", widget: "image" }
            }
